import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import CookieBanner from "/app/components/CookieBanner.tsx"; // Hier importieren!

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.tsx

const Navbar = () => {
  const navs = [
    {
      label: "Home",
      href: "/",
    },
    {
      label: "FACE",
      href: "/face",
    },
    {
      label: "BODY",
      href: "/body",
    },
    {
      label: "Contact",
      href: "/contact",
    },
  ];

  return (
    <nav className="bg-white border border-black">
      <ul className="flex justify-center">
        {navs.map((nav) => (
          <li
            key={nav.label}
            className="p-3 cursor-pointer hover:bg-black hover:text-white"
          >
            <Link href={nav.href}>{nav.label}</Link>
          </li>
        ))}
      </ul>
    </nav>
  );
};

function Footer() {
  return (
    <footer className="bg-gray-200 text-center py-6">
      <p>&copy; 2025 Longevity Beauty by LongvityCenter® </p>
    </footer>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Navbar />
        {children}

        <Footer />
      </body>
    </html>
  );
}
