import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
// SCHRITT 1: Importiere deinen CookieBanner (Pfad eventuell anpassen!)
import CookieBanner from "./components/CookieBanner";
// NEU: Importiere den Client-Footer
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Longevity Beauty",
  description: "Generated by create next app",
};

const Navbar = () => {
  const navs = [
    { label: "Home", href: "/" },
    { label: "FACE", href: "/face" },
    { label: "BODY", href: "/body" },
    { label: "Contact", href: "/contact" },
  ];

  return (
    <nav className="bg-white border border-black">
      <ul className="flex justify-center">
        {navs.map((nav) => (
          <li
            key={nav.label}
            className="p-3 cursor-pointer hover:bg-black hover:text-white"
          >
            <Link href={nav.href}>{nav.label}</Link>
          </li>
        ))}
      </ul>
    </nav>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className="antialiased">
        {/* SCHRITT 2: Hier den Banner einfügen */}
        <CookieBanner />

        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
